# Dependencies
highlighter:         rouge

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Haisum's Blog
tagline:             "It's not a bug, it's a feature."
description:         A blog by software engineer and food enthusiast.
url:                 https://haisum.github.io
baseurl:             https://haisum.github.io/
paginate:            5
google_analytics_id: UA-56228338-1

# About/contact
author:
  name:              Haisum Bhatti
  url:               https://facebook.com/haisum
  email:             haisumbhatti@gmail.com

# Custom vars
version:             1.0.0

gems:
  - jekyll-feed